InteractiveLearning/Models/TutorialsModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace InteractiveLearning.Models
{
    public class TutorialsModels
    {
        public int TutorialID { get; set; }

        public string TutorialTitle { get; set; }
    }

}

InteractiveLearning/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InteractiveLearning.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "CC & Co.";
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Chris Campbell";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Feel free to contact us at any time.";

            return View();
        }

        public ActionResult Tutorials()
        {
            ViewBag.Message = "Your list of Tutorials.";

            return View();
        }

        public ActionResult AddingContent()
        {
            ViewBag.Message = "Coming soon!";

            return View();
        }

        public ActionResult Maintenance()
        {
            ViewBag.Message = "This page is currently undergoing maintenance!";

            return View();
        }
    }
}

InteractiveLearning/Controllers/TutorialsController.cs
using InteractiveLearning.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InteractiveLearning.Controllers
{
    public class TutorialsController : Controller
    {
        // GET: Tutorials
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult  MicrosoftExcel()
        {
            TutorialsModels model = new TutorialsModels();
            model.TutorialTitle = "Choose which Microsoft Excel tutorial works for you:";
            return View(model);
        }

        [HttpPost]
        public ActionResult MicrosoftExcel(TutorialsModels model)
        {
            switch(model.TutorialID)
            {
                case 0:
                    return IntroToExcel(model);
                default:
                    return Index();                
            }
        }

        public ActionResult IntroToExcel(TutorialsModels model)
        {
            model.TutorialTitle = "Introduction to Microsoft Excel";
            return View("MicrosoftExcel/IntroToExcel", model);
        }

        public ActionResult CellBasics(TutorialsModels model)
        {
            model.TutorialTitle = "Microsoft Excel: Learning Cell Basics";
            return View("MicrosoftExcel/CellBasics", model);
        }


    }
}

InteractiveLearning/Views/Home/About.cshtml
@{
    ViewBag.Title = "About:";
}
<div class="col-xs-12">
    <h2>@ViewBag.Title</h2>
    <h2>@ViewBag.Message</h2>

    <p><a href="mailto:campbellc8@students.rowan.edu?Subject=Hey%20Chris" target="_top">campbellc8@students.rowan.edu</a></p>
    <p class="text">Kimble Byrd</p>
    <p class="text">New Venture Development</p>
    <p class="text">Monday, Wednesday - 2 PM</p>

</div>

InteractiveLearning/Views/Home/AddingContent.cshtml
<div class="col-xs-12">
    <h1>@ViewBag.Message</h1>
    <div class="col-xs-12 col-sm-4 adding-content" style="margin: auto;">
        <img style="border-left: 1px solid lightblue;max-width: 250px; max-height:400px;" class="img-responsive" src="~/Content/Images/strong-cartoon-brain.jpg" />
    </div>
    <div class="col-xs-12 col-sm-left-offset-1 col-sm-7">
        <p class="text">This is being updated! We are actively adding content for your learning pleasure!</p>
        <p class="text">Thanks for patiently waiting.</p>
        <p class="text">Plenty of more to pick from!</p>
        <p class="text">Browse around: @Html.ActionLink("here", "Index", "Tutorials")!</p>
    </div>
</div>

InteractiveLearning/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact:";
}

<div class="col-xs-12">
    <h2>@ViewBag.Title</h2>
    <h3>@ViewBag.Message</h3>


    <address>
        <strong>Personal:</strong>  <a href="mailto:campbellc8@students.rowan.edu?Subject=Hey%20Chris">CCPersonal@interactivetutorials.com</a><br />
        <strong>Support:</strong>   <a href="mailto:campbellc8@students.rowan.edu?Subject=Support">CCSupport@interactivetutorials.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:campbellc8@students.rowan.edu?Subject=Marketing">CCMarketing@interactivetutorials.com</a>
    </address>

</div>

InteractiveLearning/Views/Home/Index.cshtml
@{
    ViewBag.Title = "CC & Co.";
}

<div class="row col-xs-12" style="margin-bottom: 10px;">
    <h2 style="text-align: center;">If you want to stay up to par with today's technology, you're in the right place.</h2>
</div>
<div class="col-xs-12 col-sm-7 info-section" style="margin-top: 15px;">
    @Html.Partial("Partials/_InfoSection")
</div>

<div class="col-xs-12 col-sm-5 popular-section">
    @Html.Partial("Partials/_PopularSection")
</div>

InteractiveLearning/Views/Home/Maintenance.cshtml
<div class="col-xs-12">
    <h1>@ViewBag.Message</h1>
    <div class="col-xs-12 col-sm-4 maintenance" style="margin: auto;">
        <img style="border-left: 1px solid lightblue;max-width: 250px; max-height:200px;" class="img-responsive"src="~/Content/Images/gears.png" />
    </div>
    <div class="col-xs-12 col-sm-left-offset-1 col-sm-7">
        <p class="text">Sorry about that, but we are trying to keep up with our most popular content.</p>
        <p class="text">This will mean shorter downtime and better, more effective tutorials later!</p>
        <p class="text">Thanks for patiently waiting.</p>
        <p class="text">Plenty of more to pick from!</p>
        <p class="text">Browse around: @Html.ActionLink("here", "Index", "Tutorials")!</p>
    </div>
</div>

InteractiveLearning/Views/Home/Partials/_InfoSection.cshtml
<div class="col-xs-12 visible-xs">
    <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Hey! Thanks for checking out CC &amp; Co. Definitely try out one of our new tutorials! Microsoft Excel is our highest rated yet!</p>&mdash; Chris Campbell (projectsbychris) <a href="https://twitter.com/projectsbychris/status/935342562684096513?ref_src=twsrc%5Etfw">November 28, 2017</a></blockquote>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>
<div class="row col-xs-12 buffer">
    <p>This is the only place to find FREE, EASY, and INTERACTIVE tutorials to help you learn the most popular applications to date.</p>
</div>
<div class="row col-xs-12" style="text-align: center;" ><img class="img-responsive" src="~/Content/Images/people-office.jpg" /></div>
<div class="row col-xs-12 buffer" style="margin-top: 10px;">
    <p>We have tutorials on all the latest and greatest software programs that will aid you in finding what you are best at.</p>
</div>

InteractiveLearning/Views/Home/Partials/_PopularSection.cshtml
<h3 style="color: indigo; text-decoration: underline;">Popular Right Now:</h3>
<div class="row col-sm-12 excel">
    <div class="col-sm-3 img-wrapper">
        <img class="img-responsive" src="~/Content/Images/Microsoft-Excel-Mac-icon.png" />
    </div>
    <div class="col-sm-9">
        <h3>@Html.ActionLink("Learn Microsoft Excel >", "MicrosoftExcel", "Tutorials")</h3>
        <p>One of the most popular programs in today's workforce.</p>
    </div>
</div>

<div class="row col-sm-12 powerpoint">
    <div class="col-sm-3 img-wrapper">
        <img class="img-responsive" src="~/Content/Images/Microsoft-PowerPoint-Mac-icon.png" />
    </div>
    <div class="col-sm-9 img-wrapper">
        <h3>@Html.ActionLink("Learn Microsoft PowerPoint >", "AddingContent", "Home")</h3>
        <p>Tips to help maximize and increase efficiency.</p>
    </div>
</div>

<div class="row col-sm-12 word">
    <div class="col-sm-3 img-wrapper">
        <img class="word-icon img-responsive" src="~/Content/Images/Microsoft-Word-Mac-icon.png" />
    </div>
    <div class="col-sm-9">
        <h3>@Html.ActionLink("Learn Microsoft Word >", "Maintenance", "Home")</h3>
        <p>Ways to improve your typing and fix those pesky spelling errors.</p>
    </div>
</div>

<div class="row col-sm-12 text-more" style="margin-top: 25px;">
    <div class="col-sm-10 col-sm-offset-2">
        <p>Plenty of more to pick from!</p>
        <p>Browse around: @Html.ActionLink("here", "Index", "Tutorials")!</p>
    </div>
</div>

InteractiveLearning/Views/Shared/_Layout.cshtml
@{ 
    //todo - dynamic page subheadlines
    ViewBag.SubHeadline = "Try one of our classes today for free.";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive Tutorials - CC &amp; Co.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="container-fluid main-wrapper">
        <div class="col-xs-12 leaderboard">
            <h1>Interactive Tutorials</h1>
            <div class="col-xs-12 col-sm-7 headline" style="margin-top: 20px;">
                <p class="lead">Easiest &amp; fastest way to learn!</p>
                <p class="lead">@ViewBag.SubHeadline</p>
            </div>
            <div class="col-xs-12 col-sm-5 hidden-xs">
                <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Hey! Thanks for checking out CC &amp; Co. Definitely try out one of our new tutorials! Microsoft Excel is our highest rated yet!</p>&mdash; Chris Campbell (projectsbychris) <a href="https://twitter.com/projectsbychris/status/935342562684096513?ref_src=twsrc%5Etfw">November 28, 2017</a></blockquote>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
        </div>
        <div class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Tutorials", "Index", "Tutorials")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @*@Html.Partial("_LoginPartial")*@
                </div>
            </div>
        </div>
        <div class="row col-xs-12 body-content" style="margin: 0; padding: 0;">
            @RenderBody()
        </div>
        <div class="row col-xs-12 col-sm-12 footer" style="min-height: 80px; padding:25px;margin:0;">
            <hr />
            <p class="small-link">&copy; @DateTime.Now.Year - CC &amp; Co<sup>&copy;</sup></p>
            <p class="small-link">@Html.ActionLink("Home", "Index", "Home")</p>
            <p class="small-link">@Html.ActionLink("Tutorials", "Index", "Tutorials")</p>
            <p class="small-link">@Html.ActionLink("About", "About", "Home")</p>
            <p class="small-link">@Html.ActionLink("Contact", "Contact", "Home")</p>
        </div>
    </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

</body>
</html>

InteractiveLearning/Views/Tutorials/Index.cshtml
<div class="row col-xs-12">
    <h2>Choose a Program to Start Learning:</h2>
    <p>We offer a wide variety of tutorials. Please explore below and start learning today. We are constantly updating and adding new content. Always check our homepage for the latest news.</p>
</div>
<div class="row col-xs-12 col-sm-12 choose-program">
    <div class="col-xs-12 col-sm-2 img-wrapper">
        <img class="img-responsive" src="~/Content/Images/Microsoft-Excel-Mac-icon.png" />
    </div>
    <div class="col-xs-12 col-sm-10 program">
        <h3>@Html.ActionLink("Microsoft Excel >", "MicrosoftExcel")</h3>
        <p class="program-text">One of our most popular courses to date. Start your new home budget or track your monthly bills with the ease of a few clicks. For all different levels of experience!</p>
    </div>
</div>
<div class="row col-xs-12 col-sm-12 choose-program">
    <div class="col-xs-12 col-sm-2 img-wrapper">
        <img class="img-responsive" src="~/Content/Images/Microsoft-PowerPoint-Mac-icon.png" />
    </div>
    <div class="col-xs-12 col-sm-10 program">
        <h3>@Html.ActionLink("Microsoft PowerPoint >", "AddingContent", "Home")</h3>
        <p class="program-text">PowerPoint can really give you the advantage when used properly! Make those boring presentations exciting and aesthetically pleasing. For all different levels of experience!</p>
    </div>
</div>
<div class="row col-xs-12 col-sm-12 choose-program">
    <div class="col-xs-12 col-sm-2 img-wrapper">
        <img style="max-width: 125px;max-height:125px;"class="img-responsive" src="~/Content/Images/Microsoft-Word-Mac-icon.png" />
    </div>
    <div class="col-xs-12 col-sm-10 program">
        <h3>@Html.ActionLink("Learn Microsoft Word >", "Maintenance", "Home")</h3>
        <p class="program-text">A powerful tool; Word has tons of hidden secrets that can help you perfect that essay you've been procrastinating to write! Word can also be used for other purposes besides writing! For all different levels of experience!</p>
    </div>
</div>

InteractiveLearning/Views/Tutorials/MicrosoftExcel.cshtml
@model InteractiveLearning.Models.TutorialsModels
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="excel-index">
    <div class="col-xs-12">
        <h1>Microsoft Excel<sup>&reg;</sup> 2010</h1>
    </div>
    <div class="row col-xs-12 col-sm-12">
        <div class="col-sm-8 col-sm-right-offset-4 ">
            <p>Excel 2010 is the spreadsheet application in the Microsoft Office 2010 suite. </p>
            <p>Get help organizing and calculating data in these Excel 2010 tutorials.</p>
        </div>
    </div>
    <div class="row col-xs-12 col-sm-8 tutorial-links">
        @Html.ActionLink("1. Introduction to Microsoft Excel", "IntroToExcel")
        <div class="col-xs-12"><p class="tut-descr">In this tutorial, navigate your way around and learn the very basics of what Excel can do for you! No prior experience required. All you need is the program to start.</p></div>
    </div>
    <div class="row col-xs-12 col-sm-8 tutorial-links">
        @Html.ActionLink("2. Learning Cell Basics", "CellBasics")
        <div class="col-xs-12"><p class="tut-descr">After you've figured out where everything is, this will allow you to start applying that knowledge and see what each cell can do!</p></div>
    </div>
    <div class="row col-xs-12 col-sm-8 tutorial-links">
        @Html.ActionLink("3. Modifying Cells & Updating Rows/Columns", "AddingContent", "Home")
        <div class="col-xs-12"><p class="tut-descr">Now that we know what cells are capable of, let's put that to the test. Let's add data to the cells and update our columns and rows with information.</p></div>
    </div>
</div>

InteractiveLearning/Views/Tutorials/MicrosoftExcel/CellBasics.cshtml
@model InteractiveLearning.Models.TutorialsModels

@{
    ViewBag.SubHeadline = "";
}
<div class="col-xs-12 excel-101-container">
    <h2>@Model.TutorialTitle</h2>
    <div class="col-xs-12 excel-wrapper">
        <p style="text-align: right; margin-right: 30px;" id="steps-count"></p>
        @* ----- DYNAMIC STEP TEXT ----- *@
        <div class="content-wrapper" style="min-height: 500px;">

            @* ----- INTRO PIECE ----- *@
            <div class="col-xs-12" id="step-zero">
                @Html.Partial("MicrosoftExcel/_CellBasicsPartials/_IntroSection")
            </div>

            @* ----- STEP 1 ----- *@
            <div class="col-xs-12 hidden" id="step-one">
                @Html.Partial("MicrosoftExcel/_CellBasicsPartials/_Step1")
            </div>

            @* ----- STEP 2 ----- *@
            <div class="col-xs-12 hidden" id="step-two">
                @Html.Partial("MicrosoftExcel/_CellBasicsPartials/_Step2")
            </div>

            @* ----- STEP 3 ----- *@
            <div class="col-xs-12 hidden" id="step-three">
                @Html.Partial("MicrosoftExcel/_CellBasicsPartials/_Step3")
            </div>

            @* ----- STEP 4 ----- *@
            <div class="col-xs-12 hidden" id="step-four">
                @Html.Partial("MicrosoftExcel/_CellBasicsPartials/_Step4")
            </div>

            @* ----- CONGRATS ----- *@
            <div class="col-xs-12 hidden" id="congrats">
                @Html.Partial("MicrosoftExcel/_CellBasicsPartials/_Congrats")
            </div>
        </div>
        @* ----- BUTTON SECTION ----- *@
        <div class="row col-xs-12 col-sm-12" id="click-next-text" style="text-align: right;">
            <p style="margin-right: 30px;" id="next-text">Click next to continue.</p>
        </div>
        <div class="row col-xs-12 button-wrapper">
            <div class="col-sm-6" style="text-align: left;"><button class="button hidden" id="prevBtn">&lt; Go Back</button></div>
            <div class="col-sm-6" style="text-align: right;"><button class="button" id="nextBtn">Next &gt;</button></div>
        </div>
    </div>
</div>
<div class="col-xs-12 references">
    <h3 style="font-size:16px;">References</h3>
    <p style="font-size:14px;">Goodwill Community Foundation. (n.d.). Excel 2010: Cell Basics. Retrieved November 20, 2017, from https://www.gcflearnfree.org/excel2010/cell-basics/1/ </p>
</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/cellbasics")

InteractiveLearning/Views/Tutorials/MicrosoftExcel/IntroToExcel.cshtml
@model InteractiveLearning.Models.TutorialsModels

@{
    ViewBag.SubHeadline = "";
}
<div class="col-xs-12 excel-101-container">
    <h2>@Model.TutorialTitle<sup>&reg;</sup></h2>
    <div class="col-xs-12 excel-wrapper">
        <p style="text-align: right; margin-right: 30px;" id="steps-count"></p>
        @* ----- DYNAMIC STEP TEXT ----- *@
        <div class="content-wrapper" style="min-height: 500px;">

            @* ----- INTRO PIECE ----- *@
            <div class="col-xs-12" id="step-zero">
                @Html.Partial("MicrosoftExcel/_IntroToExcelPartials/_IntroSection")
            </div>

            @* ----- STEP 1 ----- *@
            <div class="col-xs-12 hidden" id="step-one">
                @Html.Partial("MicrosoftExcel/_IntroToExcelPartials/_Step1")
            </div>

            @* ----- STEP 2 ----- *@
            <div class="col-xs-12 hidden" id="step-two">
                @Html.Partial("MicrosoftExcel/_IntroToExcelPartials/_Step2")
            </div>

            @* ----- STEP 3 ----- *@
            <div class="col-xs-12 hidden" id="step-three">
                @Html.Partial("MicrosoftExcel/_IntroToExcelPartials/_Step3")
            </div>

            @* ----- STEP 4 ----- *@
            <div class="col-xs-12 hidden" id="step-four">
                @Html.Partial("MicrosoftExcel/_IntroToExcelPartials/_Step4")
            </div>

            @* ----- STEP 5 ----- *@
            <div class="col-xs-12 hidden" id="step-five">
                @Html.Partial("MicrosoftExcel/_IntroToExcelPartials/_Step5")
            </div>
        
            @* ----- STEP 6 ----- *@
            <div class="col-xs-12 hidden" id="step-six">
                @Html.Partial("MicrosoftExcel/_IntroToExcelPartials/_Step6")
            </div>

            @* ----- CONGRATS ----- *@
            <div class="col-xs-12 hidden" id="congrats">
                @Html.Partial("MicrosoftExcel/_IntroToExcelPartials/_Congrats")
            </div>
        </div>
        @* ----- BUTTON SECTION ----- *@
        <div class="row col-xs-12 col-sm-12" id="click-next-text" style="text-align: right;">
            <p style="margin-right: 30px;" id="next-text">Click next to continue.</p>
        </div>
        <div class="row col-xs-12 button-wrapper">
            <div class="col-sm-6" style="text-align: left;"><button class="button hidden" id="prevBtn">&lt; Go Back</button></div>
            <div class="col-sm-6" style="text-align: right;"><button class="button" id="nextBtn">Next &gt;</button></div>
        </div>
    </div>
</div>
<div class="col-xs-12 references">
    <h3 style="font-size:16px;">References</h3>
    <p style="font-size:14px;" >Goodwill Community Foundation. (n.d.). Excel 2010: Getting Started with Excel. Retrieved November 20, 2017, from https://www.gcflearnfree.org/excel2010/getting-started-with-excel/1/ </p>
</div>

@Scripts.Render("~/bundles/tutorials")
@Scripts.Render("~/bundles/jquery")

InteractiveLearning/Views/Tutorials/MicrosoftExcel/_CellBasicsPartials/_Congrats.cshtml
<div class="row col-xs-12 excel-text" id="congrats-text">
    <p class="header">Congratulations!</p>
</div>
<div class="row col-xs-12 col-sm-12">
    <div class="col-xs-12 col-sm-8">
        <h2>You just learned the how to manipulate and edit the cells of Microsite Excel.</h2>
        <p>Keep the learning going and go to @Html.ActionLink("the next lesson", "AddingContent", "Home")!</p>
        <p>Try putting some of the knowledge you learned to the test! Or go back and familiarize yourself some more!</p>
    </div>
</div>

InteractiveLearning/Views/Tutorials/MicrosoftExcel/_CellBasicsPartials/_IntroSection.cshtml
<div class="row col-xs-12 excel-text"><p class="header">Introduction</p></div>
<div class="row col-xs-12 excel-text">
    You will need to know the basic ways you can work with cells and cell content in Excel to be able to use it to calculate, analyze, and organize data. In this lesson, you will learn how to select cells, insert content, and delete cells and cell content. You will also learn how to cut, copy, and paste cells; drag and drop cells; and fill cells using the fill handle.
</div>
<div class="row col-xs-12 excel-subtext">
    Cells are the basic building blocks of a worksheet. They can contain a variety of content such as text, formatting attributes, formulas, and functions. To work with cells, you'll need to know how to select them, insert content, and delete cells and cell content.
</div>
<div class="row col-xs-12">
    <div class="row col-xs-12 col-sm-12" id="image1" >
        <div style="margin-left: 275px;"><iframe width="560" height="315" src="https://www.youtube.com/embed/jQGo3dPPQoc" frameborder="0" allowfullscreen></iframe></div>
    </div>
</div>

InteractiveLearning/Views/Tutorials/MicrosoftExcel/_CellBasicsPartials/_Step1.cshtml
<div class="row col-xs-12 excel-text" id="step-one-text">
    <p class="header">The Cell</p>
</div>
<div class="row col-xs-12 col-sm-12">
    <div class="col-xs-12 col-sm-6">
        <p>Each rectangle in a worksheet is called a cell. A cell is the intersection of a row and a column.</p>
    </div>
    <div class="col-xs-12 col-sm-6" style="margin:auto;">
        <img class="img-responsive" style="margin-bottom: 15px;  max-width: 250px; max-height: 250px;"  src="~/Content/Images/cell_intro_1000.png" />
    </div>
    <div class="col-xs-12 col-sm-6">
        <p>Each cell has a name, or a cell address based on which column and row it intersects. The cell address of a selected cell appears in the name box. Here, you can see that C5 is selected.</p>
    </div>
    <div class="col-xs-12 col-sm-6" style="margin:auto;">
        <img class="img-responsive" style="margin-bottom: 15px; max-width: 250px; max-height: 250px;" src="~/Content/Images/name_box.png" />
    </div>
    <div class="col-xs-12">
        <p>You can also select multiple cells at the same time. A group of cells is known as a cell range. Rather than a single cell address, you will refer to a cell range using the cell addresses of the first and last cells in the cell range, separated by a colon. For example, a cell range that included cells A1, A2, A3, A4, and A5 would be written as A1:A5.</p>
    </div>
    <p class="desc-title">To select a cell:</p>
    <ol class="cellbasicsol">
        <li>
            Click a cell to select it. When a cell is selected, you will notice that the borders of the cell appear bold and the column heading and row heading of the cell are highlighted.
        </li>
        <li>Release your mouse. The cell will stay selected until you click another cell in the worksheet.</li>
    </ol>
    <p class="desc-title">To select multiple cells:</p>
    <ol class="cellbasicsol">
        <li>
            Click and drag your mouse until all of the adjoining cells you want are highlighted.
        </li>
        <li>Release your mouse. The cells will stay selected until you click another cell in the worksheet.</li>
    </ol>
    
</div>

InteractiveLearning/Views/Tutorials/MicrosoftExcel/_CellBasicsPartials/_Step3.cshtml
<div class="row col-xs-12 excel-text" id="step-three-text">
    <p class="header">Cell Content</p>
</div>
<div class="row col-sm-12">
    <div class="col-xs-12 col-sm-12">
        <div class="col-sm-7">
            <p class="desc-title">To copy and paste cell content:</p>
            <ol class="cellbasicsol">
                <li>Select the cells you want to copy.</li>
                <li>Click the Copy command. The border of the selected cells will change appearance.</li>
                <li>Select the cell or cells where you want to paste the content.</li>
                <li>Click the Paste command. The copied content will be entered into the highlighted cells.</li>
            </ol>
        </div>
        <div class="col-sm-5" style="display:inline-flex;">
            <img class="img-responsive" style="margin:0 15px 20px;  max-width: 2750px; max-height: 200px;" src="~/Content/Images/step3-firstimage.png" />
            <img class="img-responsive" style="margin:0 15px 20px;  max-width: 2750px; max-height: 200px;" src="~/Content/Images/step3-secondimage.png" />
        </div>
    </div>
    <div class="col-xs-12 col-sm-12">
        <div class="col-sm-7">
            <p class="desc-title">To cut and paste cell content:</p>
            <ol class="cellbasicsol">
                <li>Select the cells you want to cut.</li>
                <li>Click the Cut command. The border of the selected cells will change appearance.</li>
                <li>Select the cells where you want to paste the content.</li>
                <li>Click the Paste command. The cut content will be removed from the original cells and entered into the highlighted cells.</li>
            </ol>
        </div>
        <div class="col-sm-5" style="display:inline-flex;">
            <img class="img-responsive" style="margin:0 15px 20px;  max-width: 275px; max-height: 200px;" src="~/Content/Images/step3-thirdimage.png" />
            <img class="img-responsive" style="margin:0 15px 20px;   max-width: 275px; max-height: 200px;" src="~/Content/Images/step3-fourthimage.png" />
        </div>
    </div>
    <div class="col-xs-12 col-sm-12">
        <div class="col-sm-12">
            <p class="desc-title">To access more paste options:</p>
            <p>There are more Paste options you can access from the drop-down menu on the Paste command. These options may be convenient to advanced users who are working with cells that contain formulas or formatting.</p>
        </div>  
    </div>
</div>

InteractiveLearning/Views/Tutorials/MicrosoftExcel/_IntroToExcelPartials/_Congrats.cshtml
<div class="row col-xs-12 excel-text" id="congrats-text">
    <p class="header">Congratulations!</p>
</div>
<div class="row col-xs-12 col-sm-12">
    <div class="col-xs-12 col-sm-8">
        <h2>You just learned the basics of Microsite Excel.</h2>
        <p>Keep the learning going and go to @Html.ActionLink("the next lesson", "CellBasics", "Tutorials")!</p>
        <p>Try putting some of the knowledge you learned to the test! Or go back and familiarize yourself some more!</p>
    </div>
</div>